"""Declarative base and schema-wide conventions.

No business tables exist yet — they arrive in phase 1 (DB foundation + audit).
What lives here now is the shape every future table must follow:

* an immutable internal UUID primary key (CLAUDE.md §4, ADR 0002)
* ``TIMESTAMPTZ`` columns written in UTC, never naive local time
* deterministic constraint and index names so Alembic autogenerate is stable
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Explicit naming convention. Without this, autogenerated migrations produce
# unstable, database-assigned constraint names and Alembic cannot reliably drop
# or alter them later (AC-1.6).
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
