"""Declarative base and schema-wide conventions.

Every table follows the same shape (CLAUDE.md §4, ADR 0002):

* an immutable internal UUID primary key
* ``TIMESTAMPTZ`` columns written in UTC, never naive local time
* an ``organization_id`` on every organization-owned table (ADR 0009)
* deterministic constraint and index names so Alembic autogenerate is stable
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any, ClassVar

from sqlalchemy import ARRAY, DateTime, MetaData, Numeric, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import DeclarativeBase

# Explicit naming convention. Without this, autogenerated migrations produce
# unstable, database-assigned constraint names and Alembic cannot reliably drop
# or alter them later (AC-1.6).
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models.

    ``type_annotation_map`` fixes the Python-to-PostgreSQL mapping once, so a
    plain ``Mapped[datetime]`` can never accidentally become a naive
    ``TIMESTAMP WITHOUT TIME ZONE`` (AC-1.2), and ``Mapped[uuid.UUID]`` is
    always a real ``uuid`` column rather than a string.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map: ClassVar[dict[Any, Any]] = {
        uuid.UUID: PGUUID(as_uuid=True),
        datetime: DateTime(timezone=True),
        str: Text(),
        Decimal: Numeric(18, 4),
        dict[str, Any]: JSONB(),
        list[str]: ARRAY(Text()),
    }
