"""amazon sync runs, order lines and inventory snapshots

Revision ID: 3767ee979011
Revises: 506fd0ecc33a
Create Date: 2026-09-15 12:11:40.591880+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3767ee979011"
down_revision: str | None = "506fd0ecc33a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Hand-checked adjustments to the autogenerated schema.
#
# * `sync_status` and `trigger_type` already exist — 506fd0ecc33a created them
#   for nineyard_sync_runs. They are declared below with create_type=False so
#   this revision neither recreates them on upgrade nor drops them on
#   downgrade. Only the one enum this revision introduces is dropped.
# * The (organization_id, seller_sku, captured_at DESC) index is an expression
#   index; autogenerate renders the expression as a literal column.
# ---------------------------------------------------------------------------

#: Native enum types this revision creates. Reused types are deliberately
#: absent: dropping them here would break nineyard_sync_runs.
ENUM_TYPES: tuple[str, ...] = ("amazon_sync_job_type",)


def _drop_enum_types() -> None:
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amazon_sync_runs",
        sa.Column(
            "job_type",
            sa.Enum(
                "ORDERS_REPORT", "FBA_INVENTORY", "LISTINGS_REPORT", name="amazon_sync_job_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "COMPLETED_WITH_ERRORS",
                "FAILED",
                "CANCELLED",
                name="sync_status",
                create_type=False,
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            postgresql.ENUM("MANUAL", "SCHEDULED", name="trigger_type", create_type=False),
            server_default="MANUAL",
            nullable=False,
        ),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("marketplace_id", sa.String(length=32), nullable=False),
        sa.Column("report_id", sa.Text(), nullable=True),
        sa.Column("rows_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rows_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "error_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'RUNNING' or completed_at is null",
            name=op.f("ck_amazon_sync_runs_running_has_no_completed_at"),
        ),
        sa.CheckConstraint(
            "completed_at is null or started_at is not null",
            name=op.f("ck_amazon_sync_runs_completed_requires_started"),
        ),
        sa.CheckConstraint(
            "completed_at is null or started_at is null or completed_at >= started_at",
            name=op.f("ck_amazon_sync_runs_completed_after_started"),
        ),
        sa.CheckConstraint(
            "rows_seen >= 0 and rows_created >= 0 and rows_updated >= 0 and rows_unchanged >= 0 and rows_failed >= 0",
            name=op.f("ck_amazon_sync_runs_counts_not_negative"),
        ),
        sa.CheckConstraint(
            "window_start is null or window_end is null or window_end >= window_start",
            name=op.f("ck_amazon_sync_runs_window_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_amazon_sync_runs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
            name=op.f("fk_amazon_sync_runs_triggered_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amazon_sync_runs")),
    )
    op.create_index(
        op.f("ix_amazon_sync_runs_organization_id"),
        "amazon_sync_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_amazon_sync_runs_organization_id_job_type_status",
        "amazon_sync_runs",
        ["organization_id", "job_type", "status", "started_at"],
        unique=False,
    )
    op.create_index(
        "uq_amazon_sync_runs_running_job",
        "amazon_sync_runs",
        ["organization_id", "job_type"],
        unique=True,
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.create_table(
        "amazon_inventory_snapshots",
        sa.Column("seller_sku", sa.Text(), nullable=False),
        sa.Column("asin", sa.String(length=16), nullable=False),
        sa.Column("fnsku", sa.String(length=16), nullable=True),
        sa.Column("condition", sa.String(length=32), nullable=True),
        sa.Column("fulfillable", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("inbound_working", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("inbound_shipped", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("inbound_receiving", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("reserved_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("unfulfillable_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("researching_total", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fbm_quantity", sa.Integer(), nullable=True),
        sa.Column("amazon_last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sync_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fbm_quantity is null or fbm_quantity >= 0",
            name=op.f("ck_amazon_inventory_snapshots_fbm_quantity_not_negative"),
        ),
        sa.CheckConstraint(
            "fulfillable >= 0 and inbound_working >= 0 and inbound_shipped >= 0 and inbound_receiving >= 0 and reserved_total >= 0 and unfulfillable_total >= 0 and researching_total >= 0",
            name=op.f("ck_amazon_inventory_snapshots_quantities_not_negative"),
        ),
        sa.CheckConstraint(
            "length(trim(seller_sku)) > 0",
            name=op.f("ck_amazon_inventory_snapshots_seller_sku_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_amazon_inventory_snapshots_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["amazon_sync_runs.id"],
            name=op.f("fk_amazon_inventory_snapshots_sync_run_id_amazon_sync_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amazon_inventory_snapshots")),
    )
    op.create_index(
        op.f("ix_amazon_inventory_snapshots_organization_id"),
        "amazon_inventory_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_amazon_inventory_snapshots_sku_captured_at",
        "amazon_inventory_snapshots",
        ["organization_id", "seller_sku", sa.literal_column("captured_at DESC")],
        unique=False,
    )
    op.create_index(
        "uq_amazon_inventory_snapshots_run_sku",
        "amazon_inventory_snapshots",
        ["sync_run_id", "seller_sku"],
        unique=True,
    )
    op.create_table(
        "amazon_order_lines",
        sa.Column("amazon_order_id", sa.String(length=32), nullable=False),
        sa.Column("seller_sku", sa.Text(), nullable=False),
        sa.Column("asin", sa.String(length=16), nullable=True),
        sa.Column("quantity_ordered", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("order_status", sa.String(length=32), nullable=False),
        sa.Column("item_status", sa.String(length=32), nullable=True),
        sa.Column("fulfillment_channel", sa.String(length=16), nullable=True),
        sa.Column("sales_channel", sa.Text(), nullable=True),
        sa.Column("marketplace_id", sa.String(length=32), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("item_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("first_seen_sync_run_id", sa.UUID(), nullable=False),
        sa.Column("last_seen_sync_run_id", sa.UUID(), nullable=False),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(item_price is null) or (currency is not null)",
            name=op.f("ck_amazon_order_lines_price_requires_currency"),
        ),
        sa.CheckConstraint(
            "item_price is null or item_price >= 0",
            name=op.f("ck_amazon_order_lines_item_price_not_negative"),
        ),
        sa.CheckConstraint(
            "length(trim(amazon_order_id)) > 0",
            name=op.f("ck_amazon_order_lines_order_id_not_blank"),
        ),
        sa.CheckConstraint(
            "length(trim(seller_sku)) > 0", name=op.f("ck_amazon_order_lines_seller_sku_not_blank")
        ),
        sa.CheckConstraint(
            "quantity_ordered >= 0", name=op.f("ck_amazon_order_lines_quantity_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_sync_run_id"],
            ["amazon_sync_runs.id"],
            name=op.f("fk_amazon_order_lines_first_seen_sync_run_id_amazon_sync_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_sync_run_id"],
            ["amazon_sync_runs.id"],
            name=op.f("fk_amazon_order_lines_last_seen_sync_run_id_amazon_sync_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_amazon_order_lines_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_amazon_order_lines")),
    )
    op.create_index(
        "ix_amazon_order_lines_first_seen_sync_run_id",
        "amazon_order_lines",
        ["first_seen_sync_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_amazon_order_lines_last_seen_sync_run_id",
        "amazon_order_lines",
        ["last_seen_sync_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_amazon_order_lines_organization_id"),
        "amazon_order_lines",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_amazon_order_lines_purchase_date",
        "amazon_order_lines",
        ["organization_id", "purchase_date"],
        unique=False,
    )
    op.create_index(
        "ix_amazon_order_lines_sku_purchase_date",
        "amazon_order_lines",
        ["organization_id", "seller_sku", "purchase_date"],
        unique=False,
    )
    op.create_index(
        "uq_amazon_order_lines_order_sku",
        "amazon_order_lines",
        ["organization_id", "amazon_order_id", "seller_sku"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_amazon_order_lines_order_sku", table_name="amazon_order_lines")
    op.drop_index("ix_amazon_order_lines_sku_purchase_date", table_name="amazon_order_lines")
    op.drop_index("ix_amazon_order_lines_purchase_date", table_name="amazon_order_lines")
    op.drop_index(op.f("ix_amazon_order_lines_organization_id"), table_name="amazon_order_lines")
    op.drop_index("ix_amazon_order_lines_last_seen_sync_run_id", table_name="amazon_order_lines")
    op.drop_index("ix_amazon_order_lines_first_seen_sync_run_id", table_name="amazon_order_lines")
    op.drop_table("amazon_order_lines")
    op.drop_index("uq_amazon_inventory_snapshots_run_sku", table_name="amazon_inventory_snapshots")
    op.drop_index(
        "ix_amazon_inventory_snapshots_sku_captured_at", table_name="amazon_inventory_snapshots"
    )
    op.drop_index(
        op.f("ix_amazon_inventory_snapshots_organization_id"),
        table_name="amazon_inventory_snapshots",
    )
    op.drop_table("amazon_inventory_snapshots")
    op.drop_index(
        "uq_amazon_sync_runs_running_job",
        table_name="amazon_sync_runs",
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.drop_index(
        "ix_amazon_sync_runs_organization_id_job_type_status", table_name="amazon_sync_runs"
    )
    op.drop_index(op.f("ix_amazon_sync_runs_organization_id"), table_name="amazon_sync_runs")
    op.drop_table("amazon_sync_runs")
    # ### end Alembic commands ###

    _drop_enum_types()
