"""initial milestone 1 schema

Revision ID: 506fd0ecc33a
Revises:
Create Date: 2026-09-08 05:50:15.204847+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "506fd0ecc33a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Hand-written additions to the autogenerated schema.
#
# Alembic cannot infer any of these from the ORM metadata: an extension, a
# trigram index expressed as raw DDL, an append-only trigger, and the enum types
# that CREATE TABLE brings into being but DROP TABLE leaves behind.
# ---------------------------------------------------------------------------

# Every native enum created implicitly by the CREATE TABLE statements below.
# PostgreSQL does not drop a type when the last table using it is dropped, so
# downgrade must remove them explicitly or a later upgrade fails with
# "type already exists".
ENUM_TYPES: tuple[str, ...] = (
    "actor_type",
    "availability_event_type",
    "availability_status",
    "exception_reason",
    "exception_status",
    "file_format",
    "identifier_type",
    "import_job_status",
    "import_row_status",
    "listing_status",
    "mapping_status",
    "marketplace",
    "match_method",
    "match_result",
    "oos_status",
    "product_status",
    "source_system",
    "sync_status",
    "trigger_type",
    "vendor_status",
    "watchlist_priority",
)


def _create_extensions() -> None:
    """Enable trigram search, used by the product-name index."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")


def _drop_extensions() -> None:
    # Deliberately not dropped. The extension may be shared with other schemas
    # in the same database, and removing it is not this migration's business.
    pass


def _create_search_indexes() -> None:
    """Trigram index for substring and fuzzy product-name search.

    The btree on (organization_id, name) serves prefix and exact lookups; this
    GIN index is what makes ``name ILIKE '%...%'`` usable on a large catalog.
    """
    op.create_index(
        "ix_products_name_trgm",
        "products",
        ["name"],
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_vendors_name_trgm",
        "vendors",
        ["name"],
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )


def _drop_search_indexes() -> None:
    op.drop_index("ix_vendors_name_trgm", table_name="vendors")
    op.drop_index("ix_products_name_trgm", table_name="products")


def _create_audit_append_only_guard() -> None:
    """Make audit_events append-only in the database itself.

    CLAUDE.md §6 requires audit rows to be append-only. Enforcing that only in
    application code would leave the guarantee resting on every future caller
    remembering it; a trigger makes UPDATE and DELETE impossible for anyone
    connected to this database, including a direct psql session.
    """
    op.execute(
        """
        CREATE OR REPLACE FUNCTION audit_events_reject_mutation()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION
                'audit_events is append-only; % is not permitted', TG_OP
                USING ERRCODE = 'restrict_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_events_append_only
        BEFORE UPDATE OR DELETE ON audit_events
        FOR EACH ROW EXECUTE FUNCTION audit_events_reject_mutation();
        """
    )


def _drop_audit_append_only_guard() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events")
    op.execute("DROP FUNCTION IF EXISTS audit_events_reject_mutation()")


def _drop_enum_types() -> None:
    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")


def upgrade() -> None:
    _create_extensions()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_organizations_name_not_blank")),
        sa.CheckConstraint("slug = lower(slug)", name=op.f("ck_organizations_slug_is_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_index("uq_organizations_slug", "organizations", ["slug"], unique=True)
    op.create_table(
        "products",
        sa.Column("catalog_item_number", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("brand", sa.Text(), nullable=True),
        sa.Column("manufacturer", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("pack_size", sa.Integer(), nullable=True),
        sa.Column("unit_of_measure", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "DISCONTINUED", "ARCHIVED", name="product_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("nineyard_last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(catalog_item_number)) > 0",
            name=op.f("ck_products_catalog_item_number_not_blank"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_products_name_not_blank")),
        sa.CheckConstraint(
            "pack_size is null or pack_size > 0", name=op.f("ck_products_pack_size_positive")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_products_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(
        op.f("ix_products_organization_id"), "products", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_products_organization_id_brand", "products", ["organization_id", "brand"], unique=False
    )
    op.create_index(
        "ix_products_organization_id_name", "products", ["organization_id", "name"], unique=False
    )
    op.create_index(
        "ix_products_organization_id_status",
        "products",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_products_organization_id_catalog_item_number",
        "products",
        ["organization_id", "catalog_item_number"],
        unique=True,
    )
    op.create_table(
        "roles",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = upper(code)", name=op.f("ck_roles_code_is_uppercase")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_roles_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
    )
    op.create_index(op.f("ix_roles_organization_id"), "roles", ["organization_id"], unique=False)
    op.create_index(
        "uq_roles_organization_id_code", "roles", ["organization_id", "code"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position('@' in email) > 1", name=op.f("ck_users_email_looks_like_an_address")
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_is_lowercase")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(
        "uq_users_organization_id_email", "users", ["organization_id", "email"], unique=True
    )
    op.create_table(
        "vendors",
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "ON_HOLD", name="vendor_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'USD'"), nullable=False),
        sa.Column("timezone", sa.Text(), server_default=sa.text("'UTC'"), nullable=False),
        sa.Column("default_lead_time_days", sa.Integer(), nullable=True),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column("contact_phone", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = upper(code)", name=op.f("ck_vendors_code_is_uppercase")),
        sa.CheckConstraint(
            "currency = upper(currency)", name=op.f("ck_vendors_currency_is_uppercase")
        ),
        sa.CheckConstraint(
            "default_lead_time_days is null or default_lead_time_days >= 0",
            name=op.f("ck_vendors_lead_time_not_negative"),
        ),
        sa.CheckConstraint(
            "length(currency) = 3", name=op.f("ck_vendors_currency_is_iso_4217_length")
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_vendors_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vendors_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
    )
    op.create_index(
        op.f("ix_vendors_organization_id"), "vendors", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_vendors_organization_id_name", "vendors", ["organization_id", "name"], unique=False
    )
    op.create_index(
        "ix_vendors_organization_id_status", "vendors", ["organization_id", "status"], unique=False
    )
    op.create_index(
        "uq_vendors_organization_id_code", "vendors", ["organization_id", "code"], unique=True
    )
    op.create_table(
        "audit_events",
        sa.Column(
            "actor_type", sa.Enum("USER", "SYSTEM", "WORKER", name="actor_type"), nullable=False
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_label", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("changed_fields", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(actor_type = 'USER' and actor_user_id is not null) or (actor_type <> 'USER' and actor_user_id is null)",
            name=op.f("ck_audit_events_actor_matches_actor_type"),
        ),
        sa.CheckConstraint(
            "length(trim(action)) > 0", name=op.f("ck_audit_events_action_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(entity_type)) > 0", name=op.f("ck_audit_events_entity_type_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            # RESTRICT, not SET NULL: SET NULL makes PostgreSQL UPDATE this
            # table, which the append-only trigger refuses. A user who has acted
            # is deactivated, never deleted.
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_actor_occurred_at",
        "audit_events",
        ["organization_id", "actor_user_id", "occurred_at"],
        unique=False,
        postgresql_where=sa.text("actor_user_id is not null"),
    )
    op.create_index(
        "ix_audit_events_entity",
        "audit_events",
        ["organization_id", "entity_type", "entity_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_organization_id"), "audit_events", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_audit_events_organization_id_action",
        "audit_events",
        ["organization_id", "action"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_organization_id_occurred_at",
        "audit_events",
        ["organization_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_events_request_id",
        "audit_events",
        ["request_id"],
        unique=False,
        postgresql_where=sa.text("request_id is not null"),
    )
    op.create_table(
        "import_files",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("original_filename", sa.Text(), nullable=False),
        sa.Column("storage_uri", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("declared_mime", sa.Text(), nullable=True),
        sa.Column("detected_encoding", sa.Text(), nullable=True),
        sa.Column("uploaded_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_import_files_sha256_is_lowercase_hex")
        ),
        sa.CheckConstraint(
            "length(trim(original_filename)) > 0",
            name=op.f("ck_import_files_original_filename_not_blank"),
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_import_files_size_bytes_not_negative")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_import_files_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_import_files_uploaded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_import_files_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_files")),
    )
    op.create_index(
        op.f("ix_import_files_organization_id"), "import_files", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_import_files_vendor_id_uploaded_at",
        "import_files",
        ["vendor_id", "uploaded_at"],
        unique=False,
    )
    op.create_index(
        "uq_import_files_organization_id_sha256",
        "import_files",
        ["organization_id", "sha256"],
        unique=True,
    )
    op.create_table(
        "marketplace_listings",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("marketplace", sa.Enum("AMAZON", name="marketplace"), nullable=False),
        sa.Column("marketplace_id", sa.Text(), nullable=False),
        sa.Column("seller_sku", sa.Text(), nullable=False),
        sa.Column("asin", sa.Text(), nullable=True),
        sa.Column(
            "listing_status",
            sa.Enum("ACTIVE", "INACTIVE", "SUPPRESSED", "UNKNOWN", name="listing_status"),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column(
            "mapping_status",
            sa.Enum(
                "UNMAPPED", "PENDING", "APPROVED", "REJECTED", "SUPERSEDED", name="mapping_status"
            ),
            server_default="UNMAPPED",
            nullable=False,
        ),
        sa.Column("approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mapping_status <> 'APPROVED' or (approved_by_user_id is not null and approved_at is not null)",
            name=op.f("ck_marketplace_listings_approved_requires_approver"),
        ),
        sa.CheckConstraint(
            "length(trim(seller_sku)) > 0",
            name=op.f("ck_marketplace_listings_seller_sku_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_marketplace_listings_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_marketplace_listings_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_marketplace_listings_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_marketplace_listings")),
    )
    op.create_index(
        op.f("ix_marketplace_listings_organization_id"),
        "marketplace_listings",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_listings_organization_id_asin",
        "marketplace_listings",
        ["organization_id", "asin"],
        unique=False,
    )
    op.create_index(
        "ix_marketplace_listings_product_id", "marketplace_listings", ["product_id"], unique=False
    )
    op.create_index(
        "uq_marketplace_listings_marketplace_id_seller_sku",
        "marketplace_listings",
        ["organization_id", "marketplace", "marketplace_id", "seller_sku"],
        unique=True,
    )
    op.create_table(
        "nineyard_sync_runs",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "COMPLETED_WITH_ERRORS",
                "FAILED",
                "CANCELLED",
                name="sync_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "trigger_type",
            sa.Enum("MANUAL", "SCHEDULED", name="trigger_type"),
            server_default="MANUAL",
            nullable=False,
        ),
        sa.Column("items_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_removed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cursor", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "error_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at is null or started_at is not null",
            name=op.f("ck_nineyard_sync_runs_completed_requires_started"),
        ),
        sa.CheckConstraint(
            "completed_at is null or started_at is null or completed_at >= started_at",
            name=op.f("ck_nineyard_sync_runs_completed_after_started"),
        ),
        sa.CheckConstraint(
            "items_seen >= 0 and items_created >= 0 and items_updated >= 0 and items_unchanged >= 0 and items_removed >= 0 and items_failed >= 0",
            name=op.f("ck_nineyard_sync_runs_counts_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_nineyard_sync_runs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
            name=op.f("fk_nineyard_sync_runs_triggered_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nineyard_sync_runs")),
    )
    op.create_index(
        op.f("ix_nineyard_sync_runs_organization_id"),
        "nineyard_sync_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_nineyard_sync_runs_organization_id_status",
        "nineyard_sync_runs",
        ["organization_id", "status", "started_at"],
        unique=False,
    )
    op.create_table(
        "oos_watchlist",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("LOW", "NORMAL", "HIGH", "CRITICAL", name="watchlist_priority"),
            server_default="NORMAL",
            nullable=False,
        ),
        sa.Column("desired_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("max_unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "current_status",
            sa.Enum("IN_STOCK", "OUT_OF_STOCK", "UNKNOWN", name="oos_status"),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column("current_status_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("added_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deactivated_by_user_id", sa.UUID(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "desired_quantity is null or desired_quantity > 0",
            name=op.f("ck_oos_watchlist_desired_quantity_positive"),
        ),
        sa.CheckConstraint(
            "is_active or deactivated_at is not null",
            name=op.f("ck_oos_watchlist_inactive_entry_records_when"),
        ),
        sa.CheckConstraint(
            "max_unit_cost is null or max_unit_cost >= 0",
            name=op.f("ck_oos_watchlist_max_unit_cost_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["added_by_user_id"],
            ["users.id"],
            name=op.f("fk_oos_watchlist_added_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deactivated_by_user_id"],
            ["users.id"],
            name=op.f("fk_oos_watchlist_deactivated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_oos_watchlist_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_oos_watchlist_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_oos_watchlist_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oos_watchlist")),
    )
    op.create_index(
        op.f("ix_oos_watchlist_organization_id"), "oos_watchlist", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_oos_watchlist_organization_id_current_status",
        "oos_watchlist",
        ["organization_id", "current_status"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_oos_watchlist_organization_id_priority",
        "oos_watchlist",
        ["organization_id", "priority"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index("ix_oos_watchlist_product_id", "oos_watchlist", ["product_id"], unique=False)
    op.create_index(
        "uq_oos_watchlist_active_product_all_vendors",
        "oos_watchlist",
        ["organization_id", "product_id"],
        unique=True,
        postgresql_where=sa.text("is_active and vendor_id is null"),
    )
    op.create_index(
        "uq_oos_watchlist_active_product_vendor",
        "oos_watchlist",
        ["organization_id", "product_id", "vendor_id"],
        unique=True,
        postgresql_where=sa.text("is_active and vendor_id is not null"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("granted_by_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["users.id"],
            name=op.f("fk_user_roles_granted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_user_roles_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
    )
    op.create_index(
        op.f("ix_user_roles_organization_id"), "user_roles", ["organization_id"], unique=False
    )
    op.create_index("ix_user_roles_role_id", "user_roles", ["role_id"], unique=False)
    op.create_index(
        "uq_user_roles_user_id_role_id", "user_roles", ["user_id", "role_id"], unique=True
    )
    op.create_table(
        "vendor_import_profiles",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("file_format", sa.Enum("CSV", "XLSX", name="file_format"), nullable=False),
        sa.Column("encoding", sa.Text(), nullable=True),
        sa.Column("delimiter", sa.String(length=4), nullable=True),
        sa.Column("quote_char", sa.String(length=1), nullable=True),
        sa.Column(
            "header_row_index", sa.SmallInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("skip_rows", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("sheet_name", sa.Text(), nullable=True),
        sa.Column("sheet_index", sa.SmallInteger(), nullable=True),
        sa.Column(
            "column_map",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "normalization_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "availability_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "quantity_semantics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "price_semantics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "pack_size_handling",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("header_signature", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_format = 'XLSX' or (sheet_name is null and sheet_index is null)",
            name=op.f("ck_vendor_import_profiles_sheet_selector_requires_xlsx"),
        ),
        sa.CheckConstraint(
            "header_row_index >= 0",
            name=op.f("ck_vendor_import_profiles_header_row_index_not_negative"),
        ),
        sa.CheckConstraint(
            "sheet_name is null or sheet_index is null",
            name=op.f("ck_vendor_import_profiles_sheet_selected_by_name_or_index_not_both"),
        ),
        sa.CheckConstraint(
            "skip_rows >= 0", name=op.f("ck_vendor_import_profiles_skip_rows_not_negative")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_vendor_import_profiles_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_vendor_import_profiles_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vendor_import_profiles_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_import_profiles_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_import_profiles")),
    )
    op.create_index(
        op.f("ix_vendor_import_profiles_organization_id"),
        "vendor_import_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_vendor_import_profiles_active_name",
        "vendor_import_profiles",
        ["organization_id", "vendor_id", "name"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "uq_vendor_import_profiles_vendor_id_name_version",
        "vendor_import_profiles",
        ["organization_id", "vendor_id", "name", "version"],
        unique=True,
    )
    op.create_table(
        "vendor_products",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("vendor_sku", sa.Text(), nullable=False),
        sa.Column("normalized_vendor_sku", sa.Text(), nullable=False),
        sa.Column("vendor_description", sa.Text(), nullable=True),
        sa.Column("raw_upc", sa.Text(), nullable=True),
        sa.Column("normalized_upc", sa.Text(), nullable=True),
        sa.Column("pack_size", sa.Integer(), nullable=True),
        sa.Column("unit_of_measure", sa.Text(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column(
            "mapping_status",
            sa.Enum(
                "UNMAPPED", "PENDING", "APPROVED", "REJECTED", "SUPERSEDED", name="mapping_status"
            ),
            server_default="UNMAPPED",
            nullable=False,
        ),
        sa.Column(
            "mapping_method",
            sa.Enum(
                "UPC",
                "CATALOG_ITEM_NUMBER",
                "VENDOR_SKU_MAPPING",
                "AMAZON_SKU_MAPPING",
                "MANUAL_APPROVAL",
                name="match_method",
            ),
            nullable=True,
        ),
        sa.Column("mapping_approved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("mapping_approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "mapping_status <> 'APPROVED' or (product_id is not null and mapping_approved_at is not null)",
            name=op.f("ck_vendor_products_approved_mapping_requires_product"),
        ),
        sa.CheckConstraint(
            "product_id is null or mapping_status <> 'UNMAPPED'",
            name=op.f("ck_vendor_products_mapped_row_is_not_unmapped"),
        ),
        sa.CheckConstraint(
            "length(trim(vendor_sku)) > 0", name=op.f("ck_vendor_products_vendor_sku_not_blank")
        ),
        sa.CheckConstraint(
            "pack_size is null or pack_size > 0", name=op.f("ck_vendor_products_pack_size_positive")
        ),
        sa.ForeignKeyConstraint(
            ["mapping_approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_vendor_products_mapping_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vendor_products_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_vendor_products_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_products_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_products")),
    )
    op.create_index(
        "ix_vendor_products_normalized_upc",
        "vendor_products",
        ["organization_id", "normalized_upc"],
        unique=False,
        postgresql_where=sa.text("normalized_upc is not null"),
    )
    op.create_index(
        "ix_vendor_products_normalized_vendor_sku",
        "vendor_products",
        ["organization_id", "normalized_vendor_sku"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_products_organization_id"),
        "vendor_products",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_vendor_products_organization_id_mapping_status",
        "vendor_products",
        ["organization_id", "mapping_status"],
        unique=False,
    )
    op.create_index(
        "ix_vendor_products_product_id", "vendor_products", ["product_id"], unique=False
    )
    op.create_index(
        "uq_vendor_products_vendor_id_vendor_sku",
        "vendor_products",
        ["organization_id", "vendor_id", "vendor_sku"],
        unique=True,
    )
    op.create_table(
        "import_jobs",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("import_file_id", sa.UUID(), nullable=False),
        sa.Column("vendor_import_profile_id", sa.UUID(), nullable=True),
        sa.Column("profile_version", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "COMPLETED_WITH_ERRORS",
                "FAILED",
                "CANCELLED",
                name="import_job_status",
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("total_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("processed_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("matched_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("exception_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("skipped_rows", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "error_details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status not in ('COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED') or completed_at is not null",
            name=op.f("ck_import_jobs_terminal_status_requires_completed_at"),
        ),
        sa.CheckConstraint(
            "completed_at is null or started_at is not null",
            name=op.f("ck_import_jobs_completed_requires_started"),
        ),
        sa.CheckConstraint(
            "completed_at is null or started_at is null or completed_at >= started_at",
            name=op.f("ck_import_jobs_completed_after_started"),
        ),
        sa.CheckConstraint(
            "total_rows >= 0 and processed_rows >= 0 and matched_rows >= 0 and exception_rows >= 0 and error_rows >= 0 and skipped_rows >= 0",
            name=op.f("ck_import_jobs_counts_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["import_file_id"],
            ["import_files.id"],
            name=op.f("fk_import_jobs_import_file_id_import_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_import_jobs_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["users.id"],
            name=op.f("fk_import_jobs_triggered_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_import_jobs_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_import_profile_id"],
            ["vendor_import_profiles.id"],
            name=op.f("fk_import_jobs_vendor_import_profile_id_vendor_import_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    op.create_index(
        "ix_import_jobs_import_file_id", "import_jobs", ["import_file_id"], unique=False
    )
    op.create_index(
        op.f("ix_import_jobs_organization_id"), "import_jobs", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_import_jobs_organization_id_status",
        "import_jobs",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_import_jobs_vendor_id_created_at",
        "import_jobs",
        ["vendor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_import_jobs_active_import_file",
        "import_jobs",
        ["organization_id", "import_file_id"],
        unique=True,
        postgresql_where=sa.text("status not in ('FAILED', 'CANCELLED')"),
    )
    op.create_table(
        "product_identifiers",
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column(
            "identifier_type",
            sa.Enum(
                "CATALOG_ITEM_NUMBER",
                "UPC",
                "EAN",
                "GTIN",
                "ASIN",
                "MPN",
                "AMAZON_SKU",
                "VENDOR_SKU",
                name="identifier_type",
            ),
            nullable=False,
        ),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum("NINEYARD", "VENDOR_IMPORT", "MARKETPLACE", "MANUAL", name="source_system"),
            nullable=False,
        ),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("marketplace_listing_id", sa.UUID(), nullable=True),
        sa.Column("has_valid_checksum", sa.Boolean(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(identifier_type = 'VENDOR_SKU' and vendor_id is not null and marketplace_listing_id is null) or (identifier_type = 'AMAZON_SKU' and marketplace_listing_id is not null and vendor_id is null) or (identifier_type not in ('VENDOR_SKU', 'AMAZON_SKU') and vendor_id is null and marketplace_listing_id is null)",
            name=op.f("ck_product_identifiers_context_matches_identifier_type"),
        ),
        sa.CheckConstraint(
            "length(trim(normalized_value)) > 0",
            name=op.f("ck_product_identifiers_normalized_value_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["marketplace_listing_id"],
            ["marketplace_listings.id"],
            name=op.f("fk_product_identifiers_marketplace_listing_id_marketplace_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_product_identifiers_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_identifiers_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_product_identifiers_vendor_id_vendors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_identifiers")),
    )
    op.create_index(
        op.f("ix_product_identifiers_organization_id"),
        "product_identifiers",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_product_identifiers_product_id", "product_identifiers", ["product_id"], unique=False
    )
    op.create_index(
        "ix_product_identifiers_type_normalized_value",
        "product_identifiers",
        ["organization_id", "identifier_type", "normalized_value"],
        unique=False,
    )
    op.create_index(
        "uq_product_identifiers_global_value",
        "product_identifiers",
        ["organization_id", "identifier_type", "normalized_value"],
        unique=True,
        postgresql_where=sa.text(
            "is_active and vendor_id is null and marketplace_listing_id is null"
        ),
    )
    op.create_index(
        "uq_product_identifiers_listing_value",
        "product_identifiers",
        ["organization_id", "marketplace_listing_id", "identifier_type", "normalized_value"],
        unique=True,
        postgresql_where=sa.text("is_active and marketplace_listing_id is not null"),
    )
    op.create_index(
        "uq_product_identifiers_vendor_value",
        "product_identifiers",
        ["organization_id", "vendor_id", "identifier_type", "normalized_value"],
        unique=True,
        postgresql_where=sa.text("is_active and vendor_id is not null"),
    )
    op.create_table(
        "import_job_rows",
        sa.Column("import_job_id", sa.UUID(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "normalized_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("vendor_sku", sa.Text(), nullable=True),
        sa.Column("normalized_vendor_sku", sa.Text(), nullable=True),
        sa.Column("raw_upc", sa.Text(), nullable=True),
        sa.Column("normalized_upc", sa.Text(), nullable=True),
        sa.Column("catalog_item_number", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "availability_status",
            sa.Enum(
                "AVAILABLE", "OUT_OF_STOCK", "DISCONTINUED", "UNKNOWN", name="availability_status"
            ),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "OK", "WARNING", "ERROR", "SKIPPED", name="import_row_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column(
            "match_result",
            sa.Enum("MATCHED", "AMBIGUOUS", "UNMATCHED", "SUGGESTION_ONLY", name="match_result"),
            nullable=True,
        ),
        sa.Column(
            "matched_by",
            sa.Enum(
                "UPC",
                "CATALOG_ITEM_NUMBER",
                "VENDOR_SKU_MAPPING",
                "AMAZON_SKU_MAPPING",
                "MANUAL_APPROVAL",
                name="match_method",
            ),
            nullable=True,
        ),
        sa.Column("match_priority", sa.SmallInteger(), nullable=True),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("vendor_product_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "match_result <> 'MATCHED' or (matched_by is not null and match_priority is not null and product_id is not null)",
            name=op.f("ck_import_job_rows_matched_row_records_deciding_rule"),
        ),
        sa.CheckConstraint(
            "match_priority is null or match_priority between 1 and 5",
            name=op.f("ck_import_job_rows_match_priority_within_chain"),
        ),
        sa.CheckConstraint(
            "quantity is null or quantity >= 0",
            name=op.f("ck_import_job_rows_quantity_not_negative"),
        ),
        sa.CheckConstraint(
            "row_number >= 0", name=op.f("ck_import_job_rows_row_number_not_negative")
        ),
        sa.CheckConstraint(
            "unit_cost is null or unit_cost >= 0",
            name=op.f("ck_import_job_rows_unit_cost_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_import_job_rows_import_job_id_import_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_import_job_rows_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_import_job_rows_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_product_id"],
            ["vendor_products.id"],
            name=op.f("fk_import_job_rows_vendor_product_id_vendor_products"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_job_rows")),
    )
    op.create_index(
        "ix_import_job_rows_import_job_id_status",
        "import_job_rows",
        ["import_job_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_import_job_rows_normalized_upc",
        "import_job_rows",
        ["organization_id", "normalized_upc"],
        unique=False,
        postgresql_where=sa.text("normalized_upc is not null"),
    )
    op.create_index(
        "ix_import_job_rows_normalized_vendor_sku",
        "import_job_rows",
        ["organization_id", "normalized_vendor_sku"],
        unique=False,
        postgresql_where=sa.text("normalized_vendor_sku is not null"),
    )
    op.create_index(
        op.f("ix_import_job_rows_organization_id"),
        "import_job_rows",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_import_job_rows_import_job_id_row_number",
        "import_job_rows",
        ["import_job_id", "row_number"],
        unique=True,
    )
    op.create_table(
        "source_records",
        sa.Column(
            "source_system",
            sa.Enum("NINEYARD", "VENDOR_IMPORT", "MARKETPLACE", "MANUAL", name="source_system"),
            nullable=False,
        ),
        sa.Column("source_entity_type", sa.Text(), nullable=False),
        sa.Column("source_record_id", sa.Text(), nullable=False),
        sa.Column("local_entity_type", sa.Text(), nullable=True),
        sa.Column("local_entity_id", sa.UUID(), nullable=True),
        sa.Column("nineyard_sync_run_id", sa.UUID(), nullable=True),
        sa.Column("import_job_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "payload_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_source_records_payload_sha256_is_lowercase_hex"),
        ),
        sa.CheckConstraint(
            "(local_entity_type is null) = (local_entity_id is null)",
            name=op.f("ck_source_records_local_reference_is_complete"),
        ),
        sa.CheckConstraint(
            "length(trim(source_record_id)) > 0",
            name=op.f("ck_source_records_source_record_id_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_source_records_import_job_id_import_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["nineyard_sync_run_id"],
            ["nineyard_sync_runs.id"],
            name=op.f("fk_source_records_nineyard_sync_run_id_nineyard_sync_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_source_records_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_records")),
    )
    op.create_index(
        "ix_source_records_local_entity",
        "source_records",
        ["organization_id", "local_entity_type", "local_entity_id"],
        unique=False,
        postgresql_where=sa.text("local_entity_id is not null"),
    )
    op.create_index(
        "ix_source_records_nineyard_sync_run_id",
        "source_records",
        ["nineyard_sync_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_source_records_organization_id"),
        "source_records",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_source_records_source_lookup",
        "source_records",
        ["organization_id", "source_system", "source_record_id"],
        unique=False,
    )
    op.create_index(
        "uq_source_records_identity_payload",
        "source_records",
        [
            "organization_id",
            "source_system",
            "source_entity_type",
            "source_record_id",
            "payload_sha256",
        ],
        unique=True,
    )
    op.create_table(
        "vendor_inventory_snapshots",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("vendor_product_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("import_job_id", sa.UUID(), nullable=False),
        sa.Column("quantity_available", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column(
            "availability_status",
            sa.Enum(
                "AVAILABLE", "OUT_OF_STOCK", "DISCONTINUED", "UNKNOWN", name="availability_status"
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_available is null or quantity_available >= 0",
            name=op.f("ck_vendor_inventory_snapshots_quantity_not_negative"),
        ),
        sa.CheckConstraint(
            "unit_cost is null or currency is not null",
            name=op.f("ck_vendor_inventory_snapshots_cost_requires_currency"),
        ),
        sa.CheckConstraint(
            "unit_cost is null or unit_cost >= 0",
            name=op.f("ck_vendor_inventory_snapshots_unit_cost_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_vendor_inventory_snapshots_import_job_id_import_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vendor_inventory_snapshots_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_vendor_inventory_snapshots_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_inventory_snapshots_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_product_id"],
            ["vendor_products.id"],
            name=op.f("fk_vendor_inventory_snapshots_vendor_product_id_vendor_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_inventory_snapshots")),
    )
    op.create_index(
        "ix_vendor_inventory_snapshots_availability_status",
        "vendor_inventory_snapshots",
        ["organization_id", "availability_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vendor_inventory_snapshots_organization_id"),
        "vendor_inventory_snapshots",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_vendor_inventory_snapshots_product_effective_at",
        "vendor_inventory_snapshots",
        ["organization_id", "product_id", "effective_at"],
        unique=False,
        postgresql_where=sa.text("product_id is not null"),
    )
    op.create_index(
        "ix_vendor_inventory_snapshots_vendor_product_effective_at",
        "vendor_inventory_snapshots",
        ["organization_id", "vendor_product_id", "effective_at"],
        unique=False,
    )
    op.create_index(
        "uq_vendor_inventory_snapshots_job_vendor_product",
        "vendor_inventory_snapshots",
        ["import_job_id", "vendor_product_id"],
        unique=True,
    )
    op.create_table(
        "availability_events",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("vendor_product_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=True),
        sa.Column("oos_watchlist_id", sa.UUID(), nullable=True),
        sa.Column(
            "event_type",
            sa.Enum("BECAME_AVAILABLE", "BECAME_UNAVAILABLE", name="availability_event_type"),
            nullable=False,
        ),
        sa.Column("previous_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("current_snapshot_id", sa.UUID(), nullable=False),
        sa.Column(
            "previous_status",
            sa.Enum(
                "AVAILABLE", "OUT_OF_STOCK", "DISCONTINUED", "UNKNOWN", name="availability_status"
            ),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "AVAILABLE", "OUT_OF_STOCK", "DISCONTINUED", "UNKNOWN", name="availability_status"
            ),
            nullable=False,
        ),
        sa.Column("previous_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("new_quantity", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("acknowledged_by_user_id", sa.UUID(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "acknowledged_at is null or acknowledged_by_user_id is not null",
            name=op.f("ck_availability_events_acknowledgement_names_a_user"),
        ),
        sa.CheckConstraint(
            "previous_snapshot_id is null or previous_snapshot_id <> current_snapshot_id",
            name=op.f("ck_availability_events_transition_between_distinct_snapshots"),
        ),
        sa.CheckConstraint(
            "previous_status is null or previous_status <> new_status",
            name=op.f("ck_availability_events_event_records_an_actual_change"),
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by_user_id"],
            ["users.id"],
            name=op.f("fk_availability_events_acknowledged_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["current_snapshot_id"],
            ["vendor_inventory_snapshots.id"],
            name=op.f("fk_availability_events_current_snapshot_id_vendor_inventory_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["oos_watchlist_id"],
            ["oos_watchlist.id"],
            name=op.f("fk_availability_events_oos_watchlist_id_oos_watchlist"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_availability_events_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["previous_snapshot_id"],
            ["vendor_inventory_snapshots.id"],
            name=op.f("fk_availability_events_previous_snapshot_id_vendor_inventory_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_availability_events_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_availability_events_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_product_id"],
            ["vendor_products.id"],
            name=op.f("fk_availability_events_vendor_product_id_vendor_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_events")),
    )
    op.create_index(
        op.f("ix_availability_events_organization_id"),
        "availability_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_availability_events_organization_id_detected_at",
        "availability_events",
        ["organization_id", "detected_at"],
        unique=False,
    )
    op.create_index(
        "ix_availability_events_product_detected_at",
        "availability_events",
        ["organization_id", "product_id", "detected_at"],
        unique=False,
        postgresql_where=sa.text("product_id is not null"),
    )
    op.create_index(
        "ix_availability_events_unacknowledged",
        "availability_events",
        ["organization_id", "detected_at"],
        unique=False,
        postgresql_where=sa.text("acknowledged_at is null"),
    )
    op.create_index(
        "ix_availability_events_vendor_product_id",
        "availability_events",
        ["vendor_product_id"],
        unique=False,
    )
    op.create_index(
        "uq_availability_events_snapshot_event_type",
        "availability_events",
        ["current_snapshot_id", "event_type"],
        unique=True,
    )
    op.create_table(
        "oos_status_history",
        sa.Column("oos_watchlist_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column(
            "previous_status",
            sa.Enum("IN_STOCK", "OUT_OF_STOCK", "UNKNOWN", name="oos_status"),
            nullable=True,
        ),
        sa.Column(
            "new_status",
            sa.Enum("IN_STOCK", "OUT_OF_STOCK", "UNKNOWN", name="oos_status"),
            nullable=False,
        ),
        sa.Column("vendor_inventory_snapshot_id", sa.UUID(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "previous_status is null or previous_status <> new_status",
            name=op.f("ck_oos_status_history_history_records_an_actual_change"),
        ),
        sa.ForeignKeyConstraint(
            ["oos_watchlist_id"],
            ["oos_watchlist.id"],
            name=op.f("fk_oos_status_history_oos_watchlist_id_oos_watchlist"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_oos_status_history_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_oos_status_history_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_oos_status_history_vendor_id_vendors"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_inventory_snapshot_id"],
            ["vendor_inventory_snapshots.id"],
            name=op.f(
                "fk_oos_status_history_vendor_inventory_snapshot_id_vendor_inventory_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oos_status_history")),
    )
    op.create_index(
        op.f("ix_oos_status_history_organization_id"),
        "oos_status_history",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_oos_status_history_organization_id_new_status",
        "oos_status_history",
        ["organization_id", "new_status", "changed_at"],
        unique=False,
    )
    op.create_index(
        "ix_oos_status_history_product_id_changed_at",
        "oos_status_history",
        ["product_id", "changed_at"],
        unique=False,
    )
    op.create_index(
        "ix_oos_status_history_watchlist_changed_at",
        "oos_status_history",
        ["oos_watchlist_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "product_mapping_exceptions",
        sa.Column("import_job_id", sa.UUID(), nullable=True),
        sa.Column("import_job_row_id", sa.UUID(), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("vendor_product_id", sa.UUID(), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "NO_MATCH",
                "AMBIGUOUS_MATCH",
                "SUGGESTION_ONLY",
                "CONFLICTING_IDENTIFIER",
                name="exception_reason",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", name="exception_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("suggested_product_id", sa.UUID(), nullable=True),
        sa.Column("suggestion_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "candidates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "match_evaluations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("resolved_product_id", sa.UUID(), nullable=True),
        sa.Column("assigned_to_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_by_user_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'APPROVED' or (resolved_product_id is not null and resolved_by_user_id is not null and resolved_at is not null)",
            name=op.f("ck_product_mapping_exceptions_approved_requires_product_and_approver"),
        ),
        sa.CheckConstraint(
            "status <> 'PENDING' or (resolved_at is null and resolved_by_user_id is null and resolved_product_id is null)",
            name=op.f("ck_product_mapping_exceptions_pending_is_unresolved"),
        ),
        sa.CheckConstraint(
            "status <> 'REJECTED' or (resolved_by_user_id is not null and resolved_at is not null)",
            name=op.f("ck_product_mapping_exceptions_rejected_requires_approver"),
        ),
        sa.CheckConstraint(
            "suggestion_score is null or (suggestion_score >= 0 and suggestion_score <= 1)",
            name=op.f("ck_product_mapping_exceptions_suggestion_score_is_a_ratio"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_product_mapping_exceptions_assigned_to_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["import_jobs.id"],
            name=op.f("fk_product_mapping_exceptions_import_job_id_import_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["import_job_row_id"],
            ["import_job_rows.id"],
            name=op.f("fk_product_mapping_exceptions_import_job_row_id_import_job_rows"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_product_mapping_exceptions_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_product_mapping_exceptions_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_product_id"],
            ["products.id"],
            name=op.f("fk_product_mapping_exceptions_resolved_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["suggested_product_id"],
            ["products.id"],
            name=op.f("fk_product_mapping_exceptions_suggested_product_id_products"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_product_mapping_exceptions_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_product_id"],
            ["vendor_products.id"],
            name=op.f("fk_product_mapping_exceptions_vendor_product_id_vendor_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_mapping_exceptions")),
    )
    op.create_index(
        "ix_product_mapping_exceptions_assigned_to_user_id",
        "product_mapping_exceptions",
        ["assigned_to_user_id"],
        unique=False,
        postgresql_where=sa.text("assigned_to_user_id is not null"),
    )
    op.create_index(
        "ix_product_mapping_exceptions_import_job_id",
        "product_mapping_exceptions",
        ["import_job_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_mapping_exceptions_organization_id"),
        "product_mapping_exceptions",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_product_mapping_exceptions_status_created_at",
        "product_mapping_exceptions",
        ["organization_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_product_mapping_exceptions_vendor_id_status",
        "product_mapping_exceptions",
        ["vendor_id", "status"],
        unique=False,
    )
    op.create_index(
        "uq_product_mapping_exceptions_pending_vendor_product",
        "product_mapping_exceptions",
        ["organization_id", "vendor_product_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING' and vendor_product_id is not null"),
    )
    # ### end Alembic commands ###

    _create_search_indexes()
    _create_audit_append_only_guard()


def downgrade() -> None:
    _drop_audit_append_only_guard()
    _drop_search_indexes()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_product_mapping_exceptions_pending_vendor_product",
        table_name="product_mapping_exceptions",
        postgresql_where=sa.text("status = 'PENDING' and vendor_product_id is not null"),
    )
    op.drop_index(
        "ix_product_mapping_exceptions_vendor_id_status", table_name="product_mapping_exceptions"
    )
    op.drop_index(
        "ix_product_mapping_exceptions_status_created_at", table_name="product_mapping_exceptions"
    )
    op.drop_index(
        op.f("ix_product_mapping_exceptions_organization_id"),
        table_name="product_mapping_exceptions",
    )
    op.drop_index(
        "ix_product_mapping_exceptions_import_job_id", table_name="product_mapping_exceptions"
    )
    op.drop_index(
        "ix_product_mapping_exceptions_assigned_to_user_id",
        table_name="product_mapping_exceptions",
        postgresql_where=sa.text("assigned_to_user_id is not null"),
    )
    op.drop_table("product_mapping_exceptions")
    op.drop_index("ix_oos_status_history_watchlist_changed_at", table_name="oos_status_history")
    op.drop_index("ix_oos_status_history_product_id_changed_at", table_name="oos_status_history")
    op.drop_index(
        "ix_oos_status_history_organization_id_new_status", table_name="oos_status_history"
    )
    op.drop_index(op.f("ix_oos_status_history_organization_id"), table_name="oos_status_history")
    op.drop_table("oos_status_history")
    op.drop_index("uq_availability_events_snapshot_event_type", table_name="availability_events")
    op.drop_index("ix_availability_events_vendor_product_id", table_name="availability_events")
    op.drop_index(
        "ix_availability_events_unacknowledged",
        table_name="availability_events",
        postgresql_where=sa.text("acknowledged_at is null"),
    )
    op.drop_index(
        "ix_availability_events_product_detected_at",
        table_name="availability_events",
        postgresql_where=sa.text("product_id is not null"),
    )
    op.drop_index(
        "ix_availability_events_organization_id_detected_at", table_name="availability_events"
    )
    op.drop_index(op.f("ix_availability_events_organization_id"), table_name="availability_events")
    op.drop_table("availability_events")
    op.drop_index(
        "uq_vendor_inventory_snapshots_job_vendor_product", table_name="vendor_inventory_snapshots"
    )
    op.drop_index(
        "ix_vendor_inventory_snapshots_vendor_product_effective_at",
        table_name="vendor_inventory_snapshots",
    )
    op.drop_index(
        "ix_vendor_inventory_snapshots_product_effective_at",
        table_name="vendor_inventory_snapshots",
        postgresql_where=sa.text("product_id is not null"),
    )
    op.drop_index(
        op.f("ix_vendor_inventory_snapshots_organization_id"),
        table_name="vendor_inventory_snapshots",
    )
    op.drop_index(
        "ix_vendor_inventory_snapshots_availability_status", table_name="vendor_inventory_snapshots"
    )
    op.drop_table("vendor_inventory_snapshots")
    op.drop_index("uq_source_records_identity_payload", table_name="source_records")
    op.drop_index("ix_source_records_source_lookup", table_name="source_records")
    op.drop_index(op.f("ix_source_records_organization_id"), table_name="source_records")
    op.drop_index("ix_source_records_nineyard_sync_run_id", table_name="source_records")
    op.drop_index(
        "ix_source_records_local_entity",
        table_name="source_records",
        postgresql_where=sa.text("local_entity_id is not null"),
    )
    op.drop_table("source_records")
    op.drop_index("uq_import_job_rows_import_job_id_row_number", table_name="import_job_rows")
    op.drop_index(op.f("ix_import_job_rows_organization_id"), table_name="import_job_rows")
    op.drop_index(
        "ix_import_job_rows_normalized_vendor_sku",
        table_name="import_job_rows",
        postgresql_where=sa.text("normalized_vendor_sku is not null"),
    )
    op.drop_index(
        "ix_import_job_rows_normalized_upc",
        table_name="import_job_rows",
        postgresql_where=sa.text("normalized_upc is not null"),
    )
    op.drop_index("ix_import_job_rows_import_job_id_status", table_name="import_job_rows")
    op.drop_table("import_job_rows")
    op.drop_index(
        "uq_product_identifiers_vendor_value",
        table_name="product_identifiers",
        postgresql_where=sa.text("is_active and vendor_id is not null"),
    )
    op.drop_index(
        "uq_product_identifiers_listing_value",
        table_name="product_identifiers",
        postgresql_where=sa.text("is_active and marketplace_listing_id is not null"),
    )
    op.drop_index(
        "uq_product_identifiers_global_value",
        table_name="product_identifiers",
        postgresql_where=sa.text(
            "is_active and vendor_id is null and marketplace_listing_id is null"
        ),
    )
    op.drop_index("ix_product_identifiers_type_normalized_value", table_name="product_identifiers")
    op.drop_index("ix_product_identifiers_product_id", table_name="product_identifiers")
    op.drop_index(op.f("ix_product_identifiers_organization_id"), table_name="product_identifiers")
    op.drop_table("product_identifiers")
    op.drop_index(
        "uq_import_jobs_active_import_file",
        table_name="import_jobs",
        postgresql_where=sa.text("status not in ('FAILED', 'CANCELLED')"),
    )
    op.drop_index("ix_import_jobs_vendor_id_created_at", table_name="import_jobs")
    op.drop_index("ix_import_jobs_organization_id_status", table_name="import_jobs")
    op.drop_index(op.f("ix_import_jobs_organization_id"), table_name="import_jobs")
    op.drop_index("ix_import_jobs_import_file_id", table_name="import_jobs")
    op.drop_table("import_jobs")
    op.drop_index("uq_vendor_products_vendor_id_vendor_sku", table_name="vendor_products")
    op.drop_index("ix_vendor_products_product_id", table_name="vendor_products")
    op.drop_index("ix_vendor_products_organization_id_mapping_status", table_name="vendor_products")
    op.drop_index(op.f("ix_vendor_products_organization_id"), table_name="vendor_products")
    op.drop_index("ix_vendor_products_normalized_vendor_sku", table_name="vendor_products")
    op.drop_index(
        "ix_vendor_products_normalized_upc",
        table_name="vendor_products",
        postgresql_where=sa.text("normalized_upc is not null"),
    )
    op.drop_table("vendor_products")
    op.drop_index(
        "uq_vendor_import_profiles_vendor_id_name_version", table_name="vendor_import_profiles"
    )
    op.drop_index(
        "uq_vendor_import_profiles_active_name",
        table_name="vendor_import_profiles",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(
        op.f("ix_vendor_import_profiles_organization_id"), table_name="vendor_import_profiles"
    )
    op.drop_table("vendor_import_profiles")
    op.drop_index("uq_user_roles_user_id_role_id", table_name="user_roles")
    op.drop_index("ix_user_roles_role_id", table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_organization_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(
        "uq_oos_watchlist_active_product_vendor",
        table_name="oos_watchlist",
        postgresql_where=sa.text("is_active and vendor_id is not null"),
    )
    op.drop_index(
        "uq_oos_watchlist_active_product_all_vendors",
        table_name="oos_watchlist",
        postgresql_where=sa.text("is_active and vendor_id is null"),
    )
    op.drop_index("ix_oos_watchlist_product_id", table_name="oos_watchlist")
    op.drop_index(
        "ix_oos_watchlist_organization_id_priority",
        table_name="oos_watchlist",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(
        "ix_oos_watchlist_organization_id_current_status",
        table_name="oos_watchlist",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_oos_watchlist_organization_id"), table_name="oos_watchlist")
    op.drop_table("oos_watchlist")
    op.drop_index("ix_nineyard_sync_runs_organization_id_status", table_name="nineyard_sync_runs")
    op.drop_index(op.f("ix_nineyard_sync_runs_organization_id"), table_name="nineyard_sync_runs")
    op.drop_table("nineyard_sync_runs")
    op.drop_index(
        "uq_marketplace_listings_marketplace_id_seller_sku", table_name="marketplace_listings"
    )
    op.drop_index("ix_marketplace_listings_product_id", table_name="marketplace_listings")
    op.drop_index("ix_marketplace_listings_organization_id_asin", table_name="marketplace_listings")
    op.drop_index(
        op.f("ix_marketplace_listings_organization_id"), table_name="marketplace_listings"
    )
    op.drop_table("marketplace_listings")
    op.drop_index("uq_import_files_organization_id_sha256", table_name="import_files")
    op.drop_index("ix_import_files_vendor_id_uploaded_at", table_name="import_files")
    op.drop_index(op.f("ix_import_files_organization_id"), table_name="import_files")
    op.drop_table("import_files")
    op.drop_index(
        "ix_audit_events_request_id",
        table_name="audit_events",
        postgresql_where=sa.text("request_id is not null"),
    )
    op.drop_index("ix_audit_events_organization_id_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_organization_id_action", table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_organization_id"), table_name="audit_events")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_index(
        "ix_audit_events_actor_occurred_at",
        table_name="audit_events",
        postgresql_where=sa.text("actor_user_id is not null"),
    )
    op.drop_table("audit_events")
    op.drop_index("uq_vendors_organization_id_code", table_name="vendors")
    op.drop_index("ix_vendors_organization_id_status", table_name="vendors")
    op.drop_index("ix_vendors_organization_id_name", table_name="vendors")
    op.drop_index(op.f("ix_vendors_organization_id"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index("uq_users_organization_id_email", table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index("uq_roles_organization_id_code", table_name="roles")
    op.drop_index(op.f("ix_roles_organization_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index("uq_products_organization_id_catalog_item_number", table_name="products")
    op.drop_index("ix_products_organization_id_status", table_name="products")
    op.drop_index("ix_products_organization_id_name", table_name="products")
    op.drop_index("ix_products_organization_id_brand", table_name="products")
    op.drop_index(op.f("ix_products_organization_id"), table_name="products")
    op.drop_table("products")
    op.drop_index("uq_organizations_slug", table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
    _drop_enum_types()
    _drop_extensions()
