"""amazon listing mapping context

Revision ID: 3de5c4e5def0
Revises: 3767ee979011
Create Date: 2026-09-15 13:28:26.178717+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3de5c4e5def0"
down_revision: str | None = "3767ee979011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Hand-checked adjustments to the autogenerated schema.
#
# * `match_method` already exists (506fd0ecc33a) — declared with
#   create_type=False so it is neither recreated nor dropped here.
# * Alembic does not compare CHECK constraints, so every check change below
#   is written by hand: two new checks on marketplace_listings, two on
#   product_mapping_exceptions, and one *rewritten* on product_identifiers
#   (an AMAZON_SKU may now exist before its listing does).
# * A downgrade that re-tightens NOT NULL would fail on real data — an
#   UNMAPPED listing without a product, or an Amazon exception without a
#   vendor. Those rows are deleted first, deliberately and loudly.
# ---------------------------------------------------------------------------

IDENTIFIER_CONTEXT_CHECK_BEFORE = (
    "(identifier_type = 'VENDOR_SKU' and vendor_id is not null"
    " and marketplace_listing_id is null)"
    " or (identifier_type = 'AMAZON_SKU' and marketplace_listing_id is not null"
    " and vendor_id is null)"
    " or (identifier_type not in ('VENDOR_SKU', 'AMAZON_SKU')"
    " and vendor_id is null and marketplace_listing_id is null)"
)
IDENTIFIER_CONTEXT_CHECK_AFTER = (
    "(identifier_type = 'VENDOR_SKU' and vendor_id is not null"
    " and marketplace_listing_id is null)"
    " or (identifier_type = 'AMAZON_SKU' and vendor_id is null)"
    " or (identifier_type not in ('VENDOR_SKU', 'AMAZON_SKU')"
    " and vendor_id is null and marketplace_listing_id is null)"
)


def _create_checks() -> None:
    op.create_check_constraint(
        op.f("ck_marketplace_listings_approved_requires_product"),
        "marketplace_listings",
        "mapping_status <> 'APPROVED' or product_id is not null",
    )
    op.create_check_constraint(
        op.f("ck_marketplace_listings_mapped_row_is_not_unmapped"),
        "marketplace_listings",
        "product_id is null or mapping_status <> 'UNMAPPED'",
    )
    op.create_check_constraint(
        op.f("ck_product_mapping_exceptions_has_a_subject"),
        "product_mapping_exceptions",
        "vendor_id is not null or marketplace_listing_id is not null",
    )
    op.create_check_constraint(
        op.f("ck_product_mapping_exceptions_vendor_product_requires_vendor"),
        "product_mapping_exceptions",
        "vendor_product_id is null or vendor_id is not null",
    )
    op.drop_constraint(
        op.f("ck_product_identifiers_context_matches_identifier_type"),
        "product_identifiers",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_product_identifiers_context_matches_identifier_type"),
        "product_identifiers",
        IDENTIFIER_CONTEXT_CHECK_AFTER,
    )


def _drop_checks() -> None:
    op.drop_constraint(
        op.f("ck_product_identifiers_context_matches_identifier_type"),
        "product_identifiers",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_product_identifiers_context_matches_identifier_type"),
        "product_identifiers",
        IDENTIFIER_CONTEXT_CHECK_BEFORE,
    )
    op.drop_constraint(
        op.f("ck_product_mapping_exceptions_vendor_product_requires_vendor"),
        "product_mapping_exceptions",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_product_mapping_exceptions_has_a_subject"),
        "product_mapping_exceptions",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_marketplace_listings_mapped_row_is_not_unmapped"),
        "marketplace_listings",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_marketplace_listings_approved_requires_product"),
        "marketplace_listings",
        type_="check",
    )


def _remove_rows_the_old_schema_cannot_hold() -> None:
    """Downgrade only. Rows that need the new columns cannot survive it."""
    op.execute("DELETE FROM product_mapping_exceptions WHERE vendor_id IS NULL")
    op.execute(
        "DELETE FROM product_identifiers WHERE identifier_type = 'AMAZON_SKU' AND marketplace_listing_id IS NULL"
    )
    op.execute("DELETE FROM marketplace_listings WHERE product_id IS NULL")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "marketplace_listings",
        sa.Column(
            "mapping_method",
            postgresql.ENUM(
                "UPC",
                "CATALOG_ITEM_NUMBER",
                "VENDOR_SKU_MAPPING",
                "AMAZON_SKU_MAPPING",
                "MANUAL_APPROVAL",
                name="match_method",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "marketplace_listings",
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column("marketplace_listings", "product_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(
        "ix_marketplace_listings_organization_id_mapping_status",
        "marketplace_listings",
        ["organization_id", "mapping_status"],
        unique=False,
    )
    op.add_column(
        "product_mapping_exceptions", sa.Column("marketplace_listing_id", sa.UUID(), nullable=True)
    )
    op.alter_column(
        "product_mapping_exceptions", "vendor_id", existing_type=sa.UUID(), nullable=True
    )
    op.create_index(
        "ix_product_mapping_exceptions_marketplace_listing_id",
        "product_mapping_exceptions",
        ["marketplace_listing_id"],
        unique=False,
        postgresql_where=sa.text("marketplace_listing_id is not null"),
    )
    op.create_index(
        "uq_product_mapping_exceptions_pending_listing",
        "product_mapping_exceptions",
        ["organization_id", "marketplace_listing_id"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING' and marketplace_listing_id is not null"),
    )
    op.create_foreign_key(
        op.f("fk_product_mapping_exceptions_marketplace_listing_id_marketplace_listings"),
        "product_mapping_exceptions",
        "marketplace_listings",
        ["marketplace_listing_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    _create_checks()


def downgrade() -> None:
    _drop_checks()
    _remove_rows_the_old_schema_cannot_hold()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_product_mapping_exceptions_marketplace_listing_id_marketplace_listings"),
        "product_mapping_exceptions",
        type_="foreignkey",
    )
    op.drop_index(
        "uq_product_mapping_exceptions_pending_listing",
        table_name="product_mapping_exceptions",
        postgresql_where=sa.text("status = 'PENDING' and marketplace_listing_id is not null"),
    )
    op.drop_index(
        "ix_product_mapping_exceptions_marketplace_listing_id",
        table_name="product_mapping_exceptions",
        postgresql_where=sa.text("marketplace_listing_id is not null"),
    )
    op.alter_column(
        "product_mapping_exceptions", "vendor_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("product_mapping_exceptions", "marketplace_listing_id")
    op.drop_index(
        "ix_marketplace_listings_organization_id_mapping_status", table_name="marketplace_listings"
    )
    op.alter_column("marketplace_listings", "product_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("marketplace_listings", "raw")
    op.drop_column("marketplace_listings", "mapping_method")
    # ### end Alembic commands ###
